# Generated by Django 2.2.6 on 2019-10-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MOMO_TASK', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrequest',
            name='rtype',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
