# Generated by Django 2.2.6 on 2019-10-26 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MOMO_TASK', '0002_mrequest_rtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mrequest',
            name='rresponseCode',
        ),
        migrations.RemoveField(
            model_name='mrequest',
            name='rresponseMessage',
        ),
        migrations.RemoveField(
            model_name='mrequest',
            name='rresponseStatus',
        ),
    ]
